development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: biblio_development
  pool: 5
  username: root
  password:
  host: localhost

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: biblio_test
  pool: 5
  username: root
  password:
  host: localhost

cucumber:
  <<: *test
